# Site settings
title: Kostiantyn Koval
person_role: iOS Developer
email: konstantin.koval1@gmail.com
description: "Blog about iOS development. Swift languages, iOS8 and more"

pygments: true
baseurl: ""
url: "http://kostiakoval.github.io"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

twitteraccount: kostiakoval
githubaccount: kostiakoval

permalink: /posts/:title

github: {
    "versions": {
        "jekyll": "1.5.1",
        "kramdown": "1.3.1",
        "liquid": "2.5.5",
        "maruku": "0.7.0",
        "rdiscount": "2.1.7",
        "redcarpet": "2.3.0",
        "RedCloth": "4.2.9",
        "jemoji": "0.1.0",
        "jekyll-mentions": "0.0.6",
        "jekyll-redirect-from": "0.3.1",
        "jekyll-sitemap": "0.2.0",
        "github-pages": "18",
        "ruby": "2.1.1"
    }
}

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Rake File Config
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim

exclude: [rake README.md]

#Comments and share From //http://blog.sendtoinc.com
inc:
 # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  true

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   false
    gplus:      true
    hn:         false

  # Analytics     
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html

plugins:     ./_plugins

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
