# Site settings
title: Konstantin Koval
person_role: iOS Developer

email: konstantin.koval1@gmail.com
description: "Blog about iOS development. Swift languages, iOS8 and more"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

twitteraccount: kostiakoval
githubaccount: konstantinkoval

permalink: /posts/:title